### ISSUE TITLE
Can i get catch downloaded data progress

### ISSUE THREAD

**Issue by liujinlongxa** [alexcrichton/AudioStreamer#41]
How can i track downloaded data progress (buffering progress indicator) like this image.![](https://cloud.githubusercontent.com/assets/4496393/5715879/e8b072f0-9b13-11e4-9a5a-15e37a717466.png)

**Comment by Bo98** [comment]
Added in 0f3e804.

The reason I didn't add it immediately was because the streamer didn't actually account for already downloaded data so any reported download progress would be useless. It was a bigger task than I thought but everything should work much better now.

The method is called `bufferProgress:` and works in exactly the same way as you would use `progress:`.
