### ISSUE TITLE
repeat/hiccup problem?

### ISSUE THREAD

**Issue by wangii** [alexcrichton/AudioStreamer#44]
I'm using the AudioStreamers in a swift project to play mp3 (vbr) while downloading from google cloud storage. I notice that sometimes in the beginning of the play, there are short repeat, blank, hiccup, jitter. I've tried to track down the issue for couple of days but just unable to find the reason. any suggestion/idea? 

thanks!

**Comment by Bo98** [comment]
I've not noticed this. Do you have an example MP3 URL I can test?

**Comment by wangii** [comment]
No. It happens randomly. Is it possible that the AudioQueueBuffer in the first batch were played multiple times?

**Comment by Bo98** [comment]
Shoudn't be but it's possible I missed something. Odd that it only happens some of the time.

I can't reproduce this and haven't noticed the issue before. Are you using iOS or OS X and which version? Is there particular (average) bitrates that are affected?

**Comment by wangii** [comment]
Right, it's random. My new theory is it's possibly related to VBR, so I switched to CBR see if it work and will report back when have any findings.

**Comment by Bo98** [comment]
I've not heard back from you, and until now had yet to discover any file which had this issue. But I have discovered that reducing the number of buffers needed to start the playback to 1 seems to cause issues which may match what you were seeing. Although I assume you had a more sensible value than 1, I'm hoping it may have been the same cause since I've not managed to reproduce any issues otherwise.

Apologies that this was only fixed now, but it was not easy to track down as I couldn't even reproduce an issue in the first place despite trying on several occasions during this time.
