### ISSUE TITLE
What's the purpose of AudioStreamer.m Lines 2178-2203

### ISSUE THREAD

**Issue by maattp** [alexcrichton/AudioStreamer#45]
I'm trying to understand the code in order to integrate it into my project. I'm stumped on what the purpose of lines 2178-2203 is, could someone explain? In practice, this chunk of code seems to set totalAudioPackets to 1000000, what's the logic here? Why is the stream being closed and reopened?

Thanks

**Comment by Bo98** [comment]
It's one of the methods of calculating duration. In an ideal world, `kAudioFileStreamProperty_AudioDataPacketCount` would always return the total audio packet count but unfortunately, it doesn't always. Lines 2178-2203 offer a manual calculation that can be used. It works like this:

1. Set `lower` to 0, `upper` to 1000000 (arbitrary limit).
2. Pick the point half way between these variables, set as `current`.
3. Try seek to this packet number.
4. If it is successful, set `lower` to `current` (total packets count will be greater than or equal to this), otherwise set `upper` to `current` (packet count will be less than this).
5. Repeat steps 2-4 until we narrow it down until `lower` and `upper` are equal (or have a difference of 1). We have found our total packet count.

The closing and reopening of the stream was just an easy way to cleanup the AudioFileStream state. Perhaps there's a better way.

This calculations are useless for livestreams which is why the `fileLength` check is there on line 2178.

**Comment by maattp** [comment]
Great, now that I see the duration: method it makes much more sense. Thanks for the quick reply @Bo98
